version: '3.8'

networks:
  roussenq:
    external: false

services:
  minio:
    image: 'minio/minio:latest'
    container_name: minio
    hostname: minio        
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - /mnt/d/volume/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123      
    networks:
      - roussenq

  trino-coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trino-coordinator
    environment:
      - TRINO_ENVIRONMENT=production
    volumes:
      - ./etc:/usr/lib/trino/etc
      - ./catalog:/etc/trino/catalog
    ports:
      - "8080:8080"
    depends_on:
      - minio
    networks:
      - roussenq         

  trino-worker:
    image: trinodb/trino:latest
    container_name: trino-worker
    environment:
      - TRINO_ENVIRONMENT=production
      - TRINO_DISCOVERY_URI=http://trino-coordinator:8080
    volumes:
      - ./etc:/usr/lib/trino/etc
      - ./catalog:/etc/trino/catalog
    depends_on:
      - trino-coordinator
    networks:
      - roussenq         

  hive-metastore:
    image: 'apache/hive:4.0.0'
    hostname: hive-metastore
    container_name: hive
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-4.0.0-bin/conf/metastore-site.xml:ro
    environment:
      SERVICE_NAME: metastore
      METASTORE_DB_HOSTNAME: minio
      HIVE_AUX_JARS_PATH: /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar:/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.367.jar
    depends_on:
      - minio
    networks:
      - roussenq     