SELECT ID_PESSOA,NOME,CPF,EMAIL,'ORACLE'AS ORIGEM FROM ORACLE.ESTUDO.PESSOA
UNION
SELECT ID,NOME,CPF,EMAIL,'POSTGRES'AS ORIGEM FROM POSTGRESQL.PESSOA.PESSOA
UNION
SELECT ID,NOME,CPF,EMAIL,'SQLSERVER'AS ORIGEM FROM SQLSERVER.PESSOA.PESSOA 
UNION
SELECT ID,NOME,CPF,EMAIL,'PARQUET'AS ORIGEM FROM MINIO.BRONZE.PESSOA_PARQUET 
UNION
SELECT CAST(ID AS INTEGER)AS ID,NOME,CPF,EMAIL,'CSV'AS ORIGEM FROM MINIO.BRONZE.PESSOA_CSV 
UNION
SELECT ID,NOME,CPF,EMAIL,'JSON'AS ORIGEM FROM MINIO.BRONZE.PESSOA_JSON
ORDER BY CPF
